#!/usr/bin/env python3
import re
import shutil
from pathlib import Path
import subprocess


# === EDIT THESE ROOTS to your environment ===
PROJECT_ROOT = Path("/home/jjhuang/scratch/jjhuang/fep_workflows")   # where systems live (code+inputs)
SCRATCH_ROOT = Path("/home/jjhuang/scratch/jjhuang/fep_workflows")   # where submit.sh cd's into
REPO_ROOT    = Path.cwd()  # run from the repo root that contains `dataset/`

# Template submit.sh (we'll fill {num} and {scratch_path})
SUBMIT_TMPL = """#!/bin/bash
#SBATCH --job-name=sys{num}
#SBATCH --account=aip-mkoz
#SBATCH --gpus-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --time=24:00:00
#SBATCH --error=sys{num}-%A.%a.err
#SBATCH --output=sys{num}-%A.%a.out
#SBATCH --mem=8G

# load modules
module --force purge
module load StdEnv/2023
module load gcc/12.3
module load openmpi/4.1.5
module load cuda/12.2
module load gromacs/2024.4

cd {scratch_path}

# initialize and activate conda
. ~/miniconda3/etc/profile.d/conda.sh
conda activate a3fe_jh

export PATH="$CONDA_PREFIX/bin:$PATH"
hash -r

unset LD_LIBRARY_PATH
export LD_LIBRARY_PATH="$CUDA_HOME/lib64"

python run_calc.py
"""

def check_ligand_charge_and_fix_pme(ligand_sdf_path: Path, template_cfg_path: Path) -> tuple[int, bool]:
    """
    Check ligand charge and automatically fix PME setting if needed.
    
    Returns:
        tuple[int, bool]: (ligand_charge, was_pme_fixed)
    """
    try:
        # Check ligand charge using BioSimSpace
        import BioSimSpace as BSS
        lig_sys = BSS.IO.readMolecules(str(ligand_sdf_path))
        lig = lig_sys[0]
        lig_charge = round(lig.charge().value())
        
        # If ligand is charged, ensure PME is set
        pme_fixed = False
        if lig_charge != 0:
            pme_fixed = patch_pme_config(template_cfg_path)
        
        return lig_charge, pme_fixed
        
    except Exception as e:
        print(f"[WARN] Could not check ligand charge for {ligand_sdf_path}: {e}")
        return 0, False

def patch_pme_config(cfg_path: Path) -> bool:
    """
    Ensure 'cutoff type = PME' in template_config.cfg.
    Adapted from find_failed_and_patch.py
    
    Returns:
        bool: True if file was modified, False if already correct or error
    """
    if not cfg_path.exists():
        print(f"[WARN] Config file not found: {cfg_path}")
        return False

    try:
        original = cfg_path.read_text()
    except Exception as e:
        print(f"[WARN] Could not read {cfg_path}: {e}")
        return False

    lines = original.splitlines()
    changed = False
    found_line = False
    out_lines = []

    for line in lines:
        if re.match(r"^\s*cutoff\s*type\s*=", line, flags=re.IGNORECASE):
            found_line = True
            if line.strip() != "cutoff type = PME":
                out_lines.append("cutoff type = PME")
                changed = True
            else:
                out_lines.append(line)
            continue
        out_lines.append(line)

    # If no cutoff type line found, add it
    if not found_line:
        out_lines.append("cutoff type = PME")
        changed = True

    if not changed:
        return False

    # Write with backup
    try:
        cfg_path.with_suffix(cfg_path.suffix + ".bak").write_text(original)
        cfg_path.write_text("\n".join(out_lines) + "\n")
        return True
    except Exception as e:
        print(f"[WARN] Could not write {cfg_path}: {e}")
        return False

def rewrite_run_calc_py(src_py: Path, dst_py: Path, base_dir: Path, input_dir: Path) -> None:
    """
    Copy run_calc.py and rewrite base_dir and input_dir strings near the end.
    Robust to spacing and different quoting; if not found, appends an override block.
    """
    text = src_py.read_text()
    # Replace calc = a3.Calculation(base_dir="...", input_dir="...")
    # We try to catch either single/double quotes and optional spaces.
    base_re = re.compile(r'(calc\s*=\s*a3\.Calculation\(\s*base_dir\s*=\s*)([\'"]).*?\2', re.DOTALL)
    input_re = re.compile(r'(,\s*input_dir\s*=\s*)([\'"]).*?\2', re.DOTALL)

    replaced = False
    def _sub_base(m):
        nonlocal replaced
        replaced = True
        return f"{m.group(1)}\"{base_dir}\""

    def _sub_input(m):
        return f"{m.group(1)}\"{input_dir}\""

    text2, n1 = base_re.subn(_sub_base, text, count=1)
    text3, n2 = input_re.subn(_sub_input, text2, count=1)

    if n1 == 0 or n2 == 0:
        # Fallback: append an override at the end (safe, explicit)
        append_block = f"""

# --- AUTO-INJECTED PATH OVERRIDES ---
# (Generated by make_systems.py)
calc.base_dir = r"{base_dir}"
calc.input_dir = r"{input_dir}"
"""
        text3 = text + append_block

    dst_py.write_text(text3)

def make_one_system(num: int):
    # Paths
    lig_sdf_name = f"mol{num}_out.sdf"
    dataset_dir  = REPO_ROOT / "dataset"
    ligands_dir  = dataset_dir / "ligands"
    src_lig_sdf  = ligands_dir / lig_sdf_name
    src_prot     = dataset_dir / "protein_final_fixed_aligned_amber.pdb"
    src_run_somd = dataset_dir / "run_somd.sh"
    src_cfg      = dataset_dir / "template_config.cfg"
    src_calc_py  = dataset_dir / "run_calc.py"

    # Validate sources
    missing = [p for p in [src_lig_sdf, src_prot, src_run_somd, src_cfg, src_calc_py] if not p.exists()]
    if missing:
        raise FileNotFoundError("Missing required template/input(s):\n" + "\n".join(str(m) for m in missing))

    # Create system dirs
    sys_name      = f"system_{num}"
    sys_proj_dir  = PROJECT_ROOT / sys_name
    sys_scratch_dir = SCRATCH_ROOT / sys_name
    sys_input_dir = sys_proj_dir / "input"
    sys_proj_dir.mkdir(parents=True, exist_ok=True)
    sys_input_dir.mkdir(parents=True, exist_ok=True)

    # Copy files
    shutil.copy2(src_prot, sys_input_dir / "protein.pdb")
    shutil.copy2(src_lig_sdf, sys_input_dir / "ligand.sdf")
    shutil.copy2(src_run_somd, sys_input_dir / "run_somd.sh")
    shutil.copy2(src_cfg,      sys_input_dir / "template_config.cfg")

    # ===== CHECK LIGAND CHARGE AND FIX PME =====
    target_ligand_sdf = sys_input_dir / "ligand.sdf"
    target_template_cfg = sys_input_dir / "template_config.cfg"
    
    print(f"🔍 Checking ligand charge for system_{num}...")
    lig_charge, pme_fixed = check_ligand_charge_and_fix_pme(target_ligand_sdf, target_template_cfg)
    
    if lig_charge == 0:
        print(f"  ✅ Ligand is neutral (charge={lig_charge}) - no PME required")
    else:
        print(f"  ⚠️  Ligand has charge {lig_charge} - PME required")
        if pme_fixed:
            print(f"  ✅ Automatically set 'cutoff type = PME' in template_config.cfg")
        else:
            print(f"  ❌ Could not automatically fix PME setting - manual intervention needed")
    # ==================================================

    # submit.sh with correct job name + cd path
    submit_text = SUBMIT_TMPL.format(num=num, scratch_path=str(sys_scratch_dir))
    (sys_proj_dir / "submit.sh").write_text(submit_text)

    # run_calc.py with correct base_dir / input_dir
    rewrite_run_calc_py(
        src_py=src_calc_py,
        dst_py=sys_proj_dir / "run_calc.py",
        base_dir=sys_proj_dir,
        input_dir=sys_input_dir
    )

    print(f"Created {sys_proj_dir}")
    print(f"  input/: protein.pdb, ligand.sdf, run_somd.sh, template_config.cfg")
    print(f"  submit.sh (job-name=sys{num}, cd {sys_scratch_dir})")
    print(f"  run_calc.py (base_dir={sys_proj_dir}, input_dir={sys_input_dir})")

def discover_nums_from_dataset() -> list[int]:
    """Find all mol{num}_out.sdf numbers under dataset/ligands/."""
    ligands_dir = REPO_ROOT / "dataset" / "ligands"
    nums = []
    for p in ligands_dir.glob("mol*_out.sdf"):
        m = re.match(r"mol(\d+)_out\.sdf$", p.name)
        if m:
            nums.append(int(m.group(1)))
    return sorted(nums)

def sbatch_submit(system_dir: Path) -> int | None:
    """Run `sbatch submit.sh` in the given system dir. Returns jobid or None on failure."""
    submit_path = system_dir / "submit.sh"
    if not submit_path.exists():
        print(f"[WARN] No submit.sh in {system_dir}, skipping submit.")
        return None
    # Make sure submit.sh is executable
    try:
        submit_path.chmod(0o755)
    except Exception:
        pass
    # Ensure scratch dir exists (the job cd's into it)
    scratch_target = SCRATCH_ROOT / system_dir.name
    scratch_target.mkdir(parents=True, exist_ok=True)
    # Submit
    try:
        res = subprocess.run(
            ["sbatch", "submit.sh"],
            cwd=str(system_dir),
            check=True,
            capture_output=True,
            text=True
        )
        out = (res.stdout or "").strip()
        m = re.search(r"Submitted batch job\s+(\d+)", out)
        jobid = int(m.group(1)) if m else None
        print(f"[SUBMITTED] {system_dir.name} → {out}")
        return jobid
    except FileNotFoundError:
        print("[ERROR] `sbatch` not found on PATH.")
        return None
    except subprocess.CalledProcessError as e:
        msg = (e.stdout or "") + "\n" + (e.stderr or "")
        print(f"[ERROR] sbatch failed for {system_dir}: \n{msg}")
        return None


def batch_fix_existing_systems(nums: list[int], dry_run: bool = False) -> None:
    """
    Check and fix PME settings for existing systems.
    Useful for retroactively fixing systems that were already created.
    """
    print(f"🔧 Batch fixing PME settings for {len(nums)} existing systems...")
    
    fixed_count = 0
    for num in nums:
        sys_input_dir = PROJECT_ROOT / f"system_{num}" / "input"
        ligand_sdf = sys_input_dir / "ligand.sdf"
        template_cfg = sys_input_dir / "template_config.cfg"
        
        if not ligand_sdf.exists() or not template_cfg.exists():
            print(f"[SKIP] system_{num}: Missing ligand.sdf or template_config.cfg")
            continue
            
        try:
            lig_charge, pme_fixed = check_ligand_charge_and_fix_pme(ligand_sdf, template_cfg)
            if lig_charge == 0:
                print(f"[OK] system_{num}: Neutral ligand, no PME needed")
            elif pme_fixed and not dry_run:
                print(f"[FIXED] system_{num}: Set PME for charged ligand (charge={lig_charge})")
                fixed_count += 1
            elif dry_run:
                print(f"[DRY-RUN] system_{num}: Would fix PME for charged ligand (charge={lig_charge})")
            else:
                print(f"[ALREADY-OK] system_{num}: PME already set for charged ligand (charge={lig_charge})")
        except Exception as e:
            print(f"[ERROR] system_{num}: {e}")
    
    if not dry_run and fixed_count > 0:
        print(f"✅ Fixed PME settings in {fixed_count} systems")
    elif dry_run:
        print("✅ Dry run completed - use --batch-fix to apply changes")

if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser(description="Create system_{num} directories with inputs and scripts.")
    ap.add_argument("--nums", nargs="*", type=int,
                    help="Specific mol numbers (e.g., 1 2 64). Overrides --range.")
    ap.add_argument("--range", nargs=2, type=int, metavar=("START", "END"),
                    help="Inclusive numeric range for mol numbers (e.g., 10 20).")
    ap.add_argument("--submit-only-range", nargs=2, type=int, metavar=("START","END"),
                    help="Submit existing PROJECT_ROOT/system_{num} for START..END (no creation).")
    ap.add_argument("--submit-only-nums", nargs="*", type=int,
                help="Submit existing PROJECT_ROOT/system_{num} for these nums (e.g., 2 5 9). No creation.")
    # New batch fix options
    ap.add_argument("--batch-fix-range", nargs=2, type=int, metavar=("START", "END"),
                    help="Fix PME settings for existing systems in range (no creation/submission).")
    ap.add_argument("--batch-fix-nums", nargs="*", type=int,
                    help="Fix PME settings for existing systems with these nums (no creation/submission).")
    ap.add_argument("--dry-run", action="store_true",
                    help="Preview PME fixes without modifying files (use with --batch-fix-*).")

    args = ap.parse_args()

    # ---- BATCH FIX MODE (fix existing systems) ----
    if args.batch_fix_range or args.batch_fix_nums:
        if args.batch_fix_range:
            start, end = args.batch_fix_range
            if start > end:
                start, end = end, start
            nums = list(range(start, end + 1))
        else:
            nums = sorted(set(args.batch_fix_nums or []))
        
        if not nums:
            raise SystemExit("[ERROR] No system numbers specified for batch fix.")
            
        batch_fix_existing_systems(nums, dry_run=args.dry_run)
        raise SystemExit(0)

    # ---- SUBMIT-ONLY MODE (no creation) ----
    if args.submit_only_range:
        start, end = args.submit_only_range
        if start > end:
            start, end = end, start
        nums = list(range(start, end + 1))
    
        systems = []
        for n in nums:
            d = PROJECT_ROOT / f"system_{n}"
            sub = d / "submit.sh"
            if sub.exists():
                systems.append(d)
            else:
                print(f"[WARN] {d} has no submit.sh — skipping (submit-only mode never creates anything)")
    
        if not systems:
            raise SystemExit("[INFO] No existing systems with submit.sh found in the requested range.")
    
        print(f"[INFO] Submit-only mode: will submit {len(systems)} systems")
        for d in systems:
            print("  -", d)
    
        import shutil as _shutil
        if _shutil.which("sbatch") is None:
            raise SystemExit("[ERROR] sbatch not found on PATH; cannot submit.")
    
        for d in systems:
            sbatch_submit(d) 
        raise SystemExit(0)     # IMPORTANT: exit so we don't fall through to creation

    # ---- SUBMIT-ONLY (explicit nums, no creation) ----
    if args.submit_only_nums:
        nums = sorted(set(args.submit_only_nums))
        systems = []
        for n in nums:
            d = PROJECT_ROOT / f"system_{n}"
            sub = d / "submit.sh"
            if sub.exists():
                systems.append(d)
            else:
                print(f"[WARN] {d} has no submit.sh — skipping (submit-only mode never creates anything)")

        if not systems:
            raise SystemExit("[INFO] No existing systems with submit.sh found for the requested nums.")

        print(f"[INFO] Submit-only mode: will submit {len(systems)} systems")
        for d in systems:
            print("  -", d)

        import shutil as _shutil
        if _shutil.which("sbatch") is None:
            raise SystemExit("[ERROR] sbatch not found on PATH; cannot submit.")

        for d in systems:
            sbatch_submit(d)
        raise SystemExit(0)  # IMPORTANT: exit so we don't fall through to creation

    if args.nums:
        nums = args.nums
    elif args.range:
        start, end = args.range
        if start > end:
            start, end = end, start
        nums = list(range(start, end + 1))
    else:
        nums = discover_nums_from_dataset()

    if not nums:
        raise SystemExit("No mol{num}_out.sdf found for the requested numbers.")

    print(f"Creating {len(nums)} systems with automatic PME checking...")
    for n in nums:
        print(f"\n--- Creating system_{n} ---")
        make_one_system(n)
    
    print(f"\n✅ Successfully created {len(nums)} systems!")
    print("Tip: Use --batch-fix-range or --batch-fix-nums to fix PME settings in existing systems")